server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置文件上传解析器
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #配置redis。
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

#配置七牛云
oss:
  # 配置七牛云中的密钥管理中的ak
  accessKey: HrGBddHak-1ywywS5IFdnFbFYhOByUyvYnkMdt07
  #配置七牛云中的密钥管理中的sk
  secretKey: J2cVtMG0BEhB9zTJrk96CcOYjGaptKh_2VuIDiMP
  #配置七牛云上设置的空间名称
  bucket: jyw-blog
  #配置七牛云的访问地址
  urlLcation: http://rmktq8jpn.bkt.clouddn.com/